project:
  type: website
  preview:
    port: 7777
  
website:
  title: "Developer Learning Wiki"
  site-url: https://your-username.github.io/your-repo-name
  navbar:
    background: white
    pinned: false
    right:
      - icon: github
        href: https://github.com/your-username
      - icon: linkedin
        href: https://linkedin.com/in/your-profile
      - icon: rss
        href: blog.xml
    left:
      - href: about.qmd
        text: About
      - text: DSA
        menu:
          - text: Overview
            href: dsa/index.qmd
          - text: Data Structures
            href: dsa/data-structures.qmd
          - text: Algorithms
            href: dsa/algorithms.qmd
          - text: Problems
            href: dsa/problems.qmd
      - text: System Design
        menu:
          - text: Overview
            href: system-design/index.qmd
          - text: Patterns
            href: system-design/patterns.qmd
          - text: Case Studies
            href: system-design/case-studies.qmd
          - text: Scalability
            href: system-design/scalability.qmd
      - text: Technical Blogs
        menu:
          - text: Overview
            href: technical-blogs/index.qmd
          - text: Breakdowns
            href: technical-blogs/breakdowns.qmd
          - text: Notes
            href: technical-blogs/notes.qmd
      - text: Books
        menu:
          - text: Overview
            href: books/index.qmd
          - text: Reading List
            href: books/reading-list.qmd
          - text: Notes
            href: books/notes.qmd
      - href: blog.qmd
        text: Blog
  sidebar:
      - id: dsa-sidebar
        style: docked
        search: true
        contents: dsa/
        sort: order
      - id: system-design-sidebar
        style: docked
        search: true
        contents: system-design/
        sort: order
      - id: technical-blogs-sidebar
        search: true
        style: docked
        contents: technical-blogs/
        sort: order
      - id: books-sidebar
        search: true
        style: docked
        contents: books/
        sort: order

format:
  html:
    theme: 
      - simplex
      - custom.scss
    js: scripts.js
    css: css/styles.css
    toc: true
    html-math-method: katex
    smooth-scroll: true
    anchor-sections: true
    include-after-body: footer.html
    page-layout: full
    filters:
      - abstract-section

